import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const folder=fs.mkdtempSync(path.join(os.tmpdir(),'community-test-'));
process.env.BOT_TOKEN='123456789:test-only';
process.env.ARBITER_TG_IDS='999';
process.env.ARBITER_MNEMONIC=Array(24).fill('test').join(' ');
process.env.PLATFORM_ADDRESS='0:'+ '0'.repeat(64);
process.env.DB_PATH=path.join(folder,'test.sqlite');
process.env.COMMUNITY_INTEGRATION_KEY='k'.repeat(48);
const {db,getDeal,joinDeal,cancelDraftDeal,setDealStatus}=require('../src/db');
const {registerListing,publishListing,setListingActive,requestListing,decideListing,getListing,getListingRequest,listingEvents,integrationAuthorized}=require('../src/listings');
const token='test_listing_123456789012';
const input={token,seller_tg_id:100,amount_units:'12000000000',description:'Gift #123 — Blue',channel_id:'-100123',escrow_enabled:true};
assert.equal(integrationAuthorized('Bearer '+'k'.repeat(48)),true);
assert.equal(integrationAuthorized('Bearer bad'),false);
assert.equal(integrationAuthorized(undefined),false);
assert.throws(()=>registerListing({...input,escrow_enabled:false}));
registerListing(input);
registerListing(input); // Idempotent create.
assert.throws(()=>registerListing({...input,amount_units:'13000000000'}));
assert.throws(()=>requestListing(token,200)); // Not published yet.
publishListing(token,{message_id:1,post_url:'https://t.me/channel/1'});
assert.throws(()=>publishListing(token,{message_id:2,post_url:'https://t.me/channel/2'}));
assert.throws(()=>requestListing(token,100)); // No self-deals.
const a=requestListing(token,200,'buyer');
assert.equal(a.seller_tg_id,null);
assert.equal(getListingRequest(a.deal_id).accepted,0);
assert.equal(requestListing(token,200).deal_id,a.deal_id); // Repeated click.
assert.throws(()=>joinDeal(a.deal_id,301,'intruder')); // Generic invite cannot bypass consent.
assert.throws(()=>decideListing(a.invite_token,301,'intruder',true));
const b=requestListing(token,201,'buyer2');
const accepted=decideListing(a.invite_token,100,'seller',true);
assert.equal(accepted.seller_tg_id,100);
assert.equal(getListing(token).status,'reserved');
assert.equal(getDeal(b.deal_id).status,'cancelled');
assert.throws(()=>decideListing(b.invite_token,100,'seller',true));
assert.throws(()=>setListingActive(token,true));
assert.throws(()=>requestListing(token,202));
assert.equal(cancelDraftDeal(a.deal_id,200),true);
assert.equal(getListing(token).status,'inactive');
setListingActive(token,true);
const c=requestListing(token,202);
decideListing(c.invite_token,100,'seller',true);
setDealStatus(c.deal_id,'completed');
assert.equal(getListing(token).status,'sold');
assert.throws(()=>setListingActive(token,true));
const token2='test_listing_second_123456';
registerListing({...input,token:token2});publishListing(token2,{message_id:3,post_url:'https://t.me/channel/3'});
const d=requestListing(token2,203);
decideListing(d.invite_token,100,'seller',true);
setDealStatus(d.deal_id,'resolved');
assert.equal(getListing(token2).status,'review');
assert.throws(()=>setListingActive(token2,true));
const token3='test_listing_expiry_123456';
registerListing({...input,token:token3});publishListing(token3,{message_id:4,post_url:'https://t.me/channel/4'});
const expired=requestListing(token3,204);
db.prepare('UPDATE community_requests SET created_at=? WHERE deal_id=?').run(1,expired.deal_id);
assert.throws(()=>decideListing(expired.invite_token,100,'seller',true));
const fresh=requestListing(token3,204);
assert.notEqual(fresh.deal_id,expired.deal_id);
assert.equal(getDeal(expired.deal_id).status,'cancelled');
const events=listingEvents(0);
assert.ok(events.some((e:any)=>e.kind==='request' && e.target_tg_id===100));
assert.ok(events.some((e:any)=>e.kind==='completed' && e.listing.status==='sold'));
assert.ok(events.some((e:any)=>e.kind==='reserved'));
db.close();fs.rmSync(folder,{recursive:true,force:true});
console.log('PASS: listing registration, ownership, consent, competing buyers, expiry, cancellation, sale, dispute and events');
